before_install:
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - git clone https://github.com/cask/cask.git $HOME/.cask
  - export PATH=$HOME/.cask/bin:$PATH
env:
  - EVM_EMACS=emacs-24.3-bin
  - EVM_EMACS=emacs-24.4-bin
install:
  - evm install $EVM_EMACS
  - evm use $EVM_EMACS
  - cask install
  - cask package
script:
  - cask exec emacs --version
  # The following $PWD is necessary for Emacs 24.3.
  - cask exec emacs --batch -f package-initialize --eval "(package-install-file (car (file-expand-wildcards \"$PWD/dist/navbar-*.tar\")))"
  - cask exec emacs --batch -f package-initialize -l test/navbar-test.el -f ert-run-tests-batch-and-exit
  - if [ "$EVM_EMACS" = "emacs-24.4-bin" ]; then
      cask exec emacs --batch -f package-initialize -l undercover --eval "(undercover \"navbar.el\")" -l navbar.el -l test/navbar-test.el -f ert-run-tests-batch-and-exit;
    fi
