env:
  - EMACS=emacs EVM_EMACS=emacs-24.3-bin
  - EMACS=emacs EVM_EMACS=emacs-24.4-bin
  - EMACS=emacs-snapshot
before_install:
  - if [ -n "$EVM_EMACS" ]; then
      sudo mkdir /usr/local/evm &&
      sudo chown travis:travis /usr/local/evm &&
      git clone https://github.com/rejeep/evm.git $HOME/.evm &&
      export PATH=$HOME/.evm/bin:$PATH &&
      evm install $EVM_EMACS &&
      evm use $EVM_EMACS;
    else
      sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
      sudo apt-get -qq update &&
      sudo apt-get -qq -f install &&
      sudo apt-get -qq install $EMACS;
    fi
  - git clone https://github.com/cask/cask.git $HOME/.cask
  - export PATH=$HOME/.cask/bin:$PATH
install:
  - cask install
  - cask package
script:
  - cask exec $EMACS --version
  # The following $PWD is necessary for Emacs 24.3.
  - cask exec $EMACS --batch -f package-initialize --eval "(package-install-file (car (file-expand-wildcards \"$PWD/dist/navbar-*.tar\")))"
  - cask exec $EMACS --batch -f package-initialize -l test/navbar-test.el -f ert-run-tests-batch-and-exit
  - if [ "$EVM_EMACS" != "emacs-24.3-bin" ]; then
      cask exec $EMACS --batch -f package-initialize -l undercover --eval "(undercover \"navbar.el\")" -l navbar.el -l test/navbar-test.el -f ert-run-tests-batch-and-exit;
    fi
