before_install:
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
env:
  - EVM_EMACS=emacs-24.3-bin
  - EVM_EMACS=emacs-24.4-bin
install:
  - evm install $EVM_EMACS
  - evm use $EVM_EMACS
script:
  - emacs --batch -f package-initialize --eval '(package-install-file "navbar.el")'
  - emacs --batch -L . -f package-initialize -l test/navbar-test.el -f ert-run-tests-batch-and-exit
