#+author: conao
#+date: <2018-10-25 Thu>

[[https://github.com/conao3/navbar.el][https://img.shields.io/github/tag/conao3/navbar.el.svg?style=flat-square]]
[[https://travis-ci.org/conao3/navbar.el][https://img.shields.io/travis/conao3/navbar.el/master.svg?style=flat-square]]
[[https://github.com/conao3/navbar.el][https://img.shields.io/github/license/conao3/navbar.el.svg?style=flat-square]]
[[https://github.com/conao3/github-header][https://files.conao3.com/github-header/gif/navbar.el.gif]]

- [[#what-is-it][What is it?]]
- [[#how-to-use][How to use?]]
- [[#welcome-pr][Welcome PR]]
- [[#special-thanks][Special Thanks]]

* What is it?
~navbar.el~ is yet another [[https://github.com/papaeye/emacs-navbar][emacs-navbar]].

navbar.el is a navigation bar for Emacs.
Just like the navbar component of [[http://getbootstrap.com/][Bootstrap]],
navbar.el can contain various components called navbar items.

1. This is the "Hello, world!" example:
   images/hello_world.png

2. The element of `navbar-item-list` may be a function which returns a property list.  To reflect the change of `navbar-item-list`, run `navbar-sync`.  `navbarx-time` displays `display-time-string` in the navbar buffer instead of the mode line:
   images/navbarx_time.png

3. `navbarx-elscreen` displays ElScreen tabs in the navbar buffer instead of the header line:
   images/navbarx_elscreen.png

* How to use?

* Develop Team
- Naoya Yamashita ([[https://github.com/conao3/leaf.el/network][conao3]])
- ROCKTAKEY ([[https://github.com/ROCKTAKEY][ROCKTAKEY]])
- papaeye ([[https://github.com/papaeye/emacs-navbar][papaeye]])
* Welcome PR
We welcome PR!
Travis Cl test ~navbar.el~ with all Emacs version 24 or above.

I think that it is difficult to prepare the environment locally, 
so I think that it is good to throw PR and test Travis for the time being!
Feel free throw PR!

* Special Thanks
Advice and comments given by [[http://emacs-jp.github.io/][Emacs-JP]]'s forum member has been a great help
in developing ~navbar.el~.

Thank you very much!!
